### ISSUE TITLE
Warnings cause pipeline crashes

### ISSUE THREAD

**Issue by Eonfge** [flathub/flatpak-builder-lint#187] opened 2023-10-09 05:32 UTC
```
Traceback (most recent call last):
  File "/app/bin/flatpak-builder-lint", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/lib/python3.11/site-packages/flatpak_builder_lint/cli.py", line 148, in main
    if args.exceptions and not args.json:
                               ^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'json'
```

See this build:
https://buildbot.flathub.org/#/builders/6/builds/71934

**Comment by bbhtt** [comment] 2023-10-09 10:28
Dupe of https://github.com/flathub/flatpak-builder-lint/issues/183

**Closed by bbhtt** 2023-10-09 10:28 UTC
